name: Build
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    env:
      NASM_VERSION: 2.15.05
      GMAKE_VERSION: 3.81
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Nasm
        shell: pwsh
        run: |
          curl.exe -OL "https://www.nasm.us/pub/nasm/releasebuilds/$($env:NASM_VERSION)/win64/nasm-$($env:NASM_VERSION)-win64.zip"
          7z x nasm-$($env:NASM_VERSION)-win64.zip -oC:/dev/nasm
          echo "C:\dev\nasm\nasm-$($env:NASM_VERSION)" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Gmake
        run: |
          curl.exe -OL "https://downloads.sourceforge.net/project/gnuwin32/make/$($env:GMAKE_VERSION)/make-$($env:GMAKE_VERSION)-bin.zip"
          7z x make-$($env:GMAKE_VERSION)-bin.zip -oC:/dev/Gmake
          echo "C:\dev\Gmake\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Download
        run: |
          python winbuild.py download
      
      - name: Build Dependencies
        run: |
          python winbuild.py builddeps
